<?php namespace ProcessWire;

/**
 * ProcessWire 'Hello world' demonstration module
 *
 * Demonstrates the Module interface and how to add hooks.
 * 
 * See README file for further links regarding module development.
 * 
 * This file is licensed under the MIT license
 * https://processwire.com/about/license/mit/
 * 
 * ProcessWire 3.x, Copyright 2016 by Ryan Cramer
 * https://processwire.com
 *
 */

class MarkupListPageTemplate extends WireData implements Module {

	/**
	 * getModuleInfo is a module required by all modules to tell ProcessWire about them
	 *
	 * @return array
	 *
	 */
	public static function getModuleInfo() {

		return array(

			// The module's title, typically a little more descriptive than the class name
			'title' => 'ListPageTemplate', 

			// version number 
			'version' => 0.1, 

			// summary is brief description of what this module is
			'summary' => 'Just a simple way to display which page template is in use.',
			
			// Optional URL to more information about the module
			'href' => 'https://strandoo.com',

			// singular=true: indicates that only one instance of the module is allowed.
			// This is usually what you want for modules that attach hooks. 
			'singular' => true, 

			// autoload=true: indicates the module should be started with ProcessWire.
			// This is necessary for any modules that attach runtime hooks, otherwise those
			// hooks won't get attached unless some other code calls the module on it's own.
			// Note that autoload modules are almost always also 'singular' (seen above).
			'autoload' => true, 
		
			// Optional font-awesome icon name, minus the 'fa-' part
			'icon' => 'plug', 
			);
	}

	/**
	 * Initialize the module
	 *
	 * ProcessWire calls this when the module is loaded. For 'autoload' modules, this will be called
	 * when ProcessWire's API is ready. As a result, this is a good place to attach hooks. 
	 *
	 */
	public function init() { 
		$this->addHookAfter('ProcessPageListRender::getPageLabel', $this, 'addPageListLabelItems');
	}

	public function addPageListLabelItems($event) {
		$page = $event->arguments('page');
		$pageTemplate = '<b class="PageListNumChildren detail" style="float:right;font-weight: normal">'.$page->template.'</b>';
		$event->return = $event->return . $pageTemplate;
	}	
}
