						<div class="sidebar-help">
							<h4>Need help or advice?</h4>
							<p>You are welcome to contact us with any questions you may have and we will be happy to help you.</p>
							<ul style="margin-bottom: 20px;">
								<li><strong>Call: <?php echo $site->site_telephone; ?></strong></li>
								<!-- <li>Mob: <?php echo $site->site_fax; ?></li> -->
								<li><strong>Email: <?php echo $site->site_email; ?></strong></li>
							</ul>
							<img src="<?php echo $config->urls->templates?>images/chas-logo.png" class="sidebar-logo chas-logo" alt="Chas logo" />
							<img src="<?php echo $config->urls->templates?>images/smas-worksafe-logo.png" class="sidebar-logo smas-logo" alt="SMAS logo" />
						</div>